name: CI Test

on:
  push:
    branches:
      - main

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print debug message
        run: echo "GitHub Actions is working!"
